#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

#xrandr --auto

xrandr --output DP-4 --mode 3440x1440 --rate 165.00 --output HDMI-0 --off
xrandr --output DP-2 --mode 3440x1440 --rate 165.00 --output HDMI-0 --off
#xrandr --output DP-4 -r 165 --output HDMI-0 --off
#xrandr --dpi 96		# Set DPI. User may want to use a larger number for larger screens.
setbg &			# set the background with the `setbg` script
picom &
udiskie &
#nm-applet &
blueberry-tray &
pipewire -c filter-chain.conf &
deadd-notification-center &
polkit-dumb-agent &
scream -o pulse -i virbr0 &

xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!	# Uncomment to use Xresources colors/settings on startup


#autostart="mpd xcompmgr dunst unclutter pipewire remapd"
#autostart= "picom deadd-notification-center"

for program in $autostart; do
	pidof -sx "$program" || "$program" &
done >/dev/null 2>&1


# make sure that only one ssh-agent process runs at a time
#if ! pgrep -u "$USER" ssh-agent > /dev/null; then
#    ssh-agent -t 1h > "$XDG_RUNTIME_DIR/ssh-agent.env"
#fi
#if [[ ! -f "$SSH_AUTH_SOCK" ]]; then
#    source "$XDG_RUNTIME_DIR/ssh-agent.env" >/dev/null
#fi

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
