#!/bin/sh

#sudo not required for some system commands
for command in mount umount sv pacman updatedb su shutdown poweroff reboot ; do
	alias $command="sudo $command"
done; unset command

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	mkd="mkdir -pv" \

# Colorize commands when possible.
alias \
	find="fd" \
	ls="eza --icons -a --group-directories-first" \
	ip="ip -color=auto" \
	ll="eza --icons -lha --group-directories-first" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	grep="rg" \
	cat="bat" \

# These common commands are just too long! Abbreviate them.

alias \
	sdn="shutdown -h now" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="pacman" \

cpr() {
  rsync --archive -hh --partial --info=stats1,progress2 --modify-window=1 "$@"
}
mvr() {
  rsync --archive -hh --partial --info=stats1,progress2 --modify-window=1 --remove-source-files "$@"
}
alias config='/usr/bin/git --git-dir=/home/lzhecz/.cfg/ --work-tree=/home/lzhecz'
alias configls="config ls-tree -r --name-only @ | cut -f1,2 -d '/' | uniq"
